#!/bin/bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║          INFOBOARD — MASTER BOOTSTRAP INSTALLER                            ║
# ║          Run once. Everything is built, installed, and running.            ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
#  Usage:
#    chmod +x bootstrap.sh && bash bootstrap.sh
#
#  What this script does:
#    1. Detects your user and environment automatically
#    2. Writes deploy.sh into your project folder
#    3. Writes the systemd service and timer unit files
#    4. Installs and enables everything
#    5. Runs the first deployment immediately
#    — You never touch another file.

set -e

# ──────────────────────────────────────────────────────────────
# COLOURS & LOGGING
# ──────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; MAGENTA='\033[0;35m'; BOLD='\033[1m'; RESET='\033[0m'

log()     { echo -e "\n${CYAN}${BOLD}▶  $1${RESET}"; }
success() { echo -e "${GREEN}  ✔  $1${RESET}"; }
warn()    { echo -e "${YELLOW}  ⚠  $1${RESET}"; }
error()   { echo -e "${RED}  ✖  $1${RESET}" >&2; }
banner()  {
  echo -e "\n${MAGENTA}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "${MAGENTA}${BOLD}  $1${RESET}"
  echo -e "${MAGENTA}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
}

# ──────────────────────────────────────────────────────────────
# HEADER
# ──────────────────────────────────────────────────────────────
clear
echo -e "${BOLD}"
cat << 'EOF'
  ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗
  ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝
  ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝
  ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝
  ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║
  ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝
     INFOBOARD — Auto-Deploy Bootstrap Installer
EOF
echo -e "${RESET}"

# ──────────────────────────────────────────────────────────────
# STEP 0 — DETECT ENVIRONMENT
# ──────────────────────────────────────────────────────────────
banner "STEP 0 — Detecting Environment"

# Detect real user even when called via sudo
if [ -n "$SUDO_USER" ]; then
  DEPLOY_USER="$SUDO_USER"
elif [ -n "$USER" ]; then
  DEPLOY_USER="$USER"
else
  DEPLOY_USER="$(whoami)"
fi

DEPLOY_HOME=$(eval echo "~${DEPLOY_USER}")

if [ ! -d "$DEPLOY_HOME" ]; then
  error "Cannot resolve home directory for user '$DEPLOY_USER'. Aborting."
  exit 1
fi

PROJECT_DIR="${DEPLOY_HOME}/Desktop/infoboard"
SYSTEMD_DIR="/etc/systemd/system"
SERVICE_NAME="infoboard-deploy@${DEPLOY_USER}"

success "User detected:   $DEPLOY_USER"
success "Home directory:  $DEPLOY_HOME"
success "Project path:    $PROJECT_DIR"
success "Service name:    ${SERVICE_NAME}.service"

# ──────────────────────────────────────────────────────────────
# STEP 1 — VERIFY PROJECT FOLDER
# ──────────────────────────────────────────────────────────────
banner "STEP 1 — Verifying Project Folder"

if [ ! -d "$PROJECT_DIR" ]; then
  error "Project folder not found: $PROJECT_DIR"
  error "Please make sure the 'infoboard' folder exists on your Desktop before running this script."
  exit 1
fi

if [ ! -d "${PROJECT_DIR}/.git" ]; then
  error "The infoboard folder exists but is NOT a Git repository."
  error "Please clone your repo into: $PROJECT_DIR"
  exit 1
fi

success "Project folder found and is a valid Git repository."

# ──────────────────────────────────────────────────────────────
# STEP 2 — WRITE deploy.sh INTO PROJECT FOLDER
# ──────────────────────────────────────────────────────────────
banner "STEP 2 — Writing deploy.sh"

log "Creating ${PROJECT_DIR}/deploy.sh ..."

cat > "${PROJECT_DIR}/deploy.sh" << 'DEPLOY_SCRIPT'
#!/bin/bash
# =============================================================================
# deploy.sh — Auto-generated by bootstrap.sh
# DO NOT EDIT MANUALLY — regenerate via bootstrap.sh if needed.
# =============================================================================

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

log()     { echo -e "${CYAN}${BOLD}$1${RESET}"; }
success() { echo -e "${GREEN}  ✔  $1${RESET}"; }
warn()    { echo -e "${YELLOW}  ⚠  $1${RESET}"; }
error()   { echo -e "${RED}  ✖  $1${RESET}" >&2; }

step() {
  echo ""
  echo -e "${BOLD}  ┌──────────────────────────────────────────┐${RESET}"
  echo -e "${BOLD}  │  [$1/4] $2${RESET}"
  echo -e "${BOLD}  └──────────────────────────────────────────┘${RESET}"
}

# ── Detect user & paths ───────────────────────────────────────
if [ -n "$SUDO_USER" ]; then
  DEPLOY_USER="$SUDO_USER"
elif [ -n "$USER" ]; then
  DEPLOY_USER="$USER"
else
  DEPLOY_USER="$(whoami)"
fi
DEPLOY_HOME=$(eval echo "~${DEPLOY_USER}")
PROJECT_DIR="${DEPLOY_HOME}/Desktop/infoboard"

echo ""
log "════════════════════════════════════════════"
log "  INFOBOARD DEPLOYMENT — $(date '+%Y-%m-%d %H:%M:%S')"
log "  User: ${DEPLOY_USER}  |  Host: $(hostname)"
log "════════════════════════════════════════════"

# ── [1/4] System security updates ────────────────────────────
step 1 "System Security Updates"

log "Refreshing apt package lists..."
sudo apt-get update -qq

if command -v unattended-upgrade &>/dev/null; then
  log "Applying security updates via unattended-upgrades..."
  sudo unattended-upgrade -v && success "Security updates applied." \
    || warn "unattended-upgrade finished with warnings — continuing."
else
  warn "unattended-upgrades not found. Installing it..."
  sudo apt-get install -y unattended-upgrades -qq
  sudo unattended-upgrade -v && success "Security updates applied." \
    || {
      warn "Falling back to apt upgrade..."
      sudo apt-get upgrade -y -qq && success "System packages upgraded."
    }
fi

# ── [2/4] Detect repo & check for updates ────────────────────
step 2 "Detecting Repo & Checking for Updates"

if [ ! -d "$PROJECT_DIR" ]; then
  error "Project folder not found: $PROJECT_DIR — aborting."
  exit 1
fi
if [ ! -d "${PROJECT_DIR}/.git" ]; then
  error "Not a git repository: $PROJECT_DIR — aborting."
  exit 1
fi
success "Project folder verified."

cd "$PROJECT_DIR"

log "Fetching from origin..."
git fetch origin

LOCAL_HEAD=$(git rev-parse HEAD)
REMOTE_HEAD=$(git rev-parse origin/main 2>/dev/null || echo "")

if [ -z "$REMOTE_HEAD" ]; then
  error "Could not resolve origin/main. Check your git remote. Aborting."
  exit 1
fi

if [ "$LOCAL_HEAD" = "$REMOTE_HEAD" ]; then
  success "Already up to date with origin/main. Nothing to deploy."
  exit 0
fi

log "New commits found — updating to origin/main..."
git reset --hard origin/main
success "Updated to: $(git rev-parse --short HEAD) — $(git log -1 --pretty=%s)"

# ── Ensure pnpm ───────────────────────────────────────────────
log "Checking for pnpm..."
if ! command -v pnpm &>/dev/null; then
  warn "pnpm not found. Bootstrapping via corepack..."
  if command -v corepack &>/dev/null; then
    sudo corepack enable
    corepack prepare pnpm@latest --activate
  else
    warn "corepack missing — installing via npm as a one-time bootstrap..."
    sudo npm install -g corepack
    sudo corepack enable
    corepack prepare pnpm@latest --activate
  fi
fi
if ! command -v pnpm &>/dev/null; then
  error "pnpm installation failed. Aborting."
  exit 1
fi
success "pnpm ready: $(pnpm --version)"

# ── [3/4] Install dependencies & build ───────────────────────
step 3 "Installing Dependencies & Building"

cd "$PROJECT_DIR"

log "Installing dependencies (frozen lockfile)..."
pnpm install --frozen-lockfile
success "Dependencies installed."

log "Building project..."
pnpm run build
success "Build complete."

# ── Ensure PM2 ───────────────────────────────────────────────
log "Checking for PM2..."
if ! command -v pm2 &>/dev/null; then
  warn "PM2 not found. Installing globally via pnpm..."
  pnpm add -g pm2
fi
if ! command -v pm2 &>/dev/null; then
  error "PM2 installation failed. Aborting."
  exit 1
fi
success "PM2 ready: $(pm2 --version)"

# ── [4/4] Restart via PM2 ────────────────────────────────────
step 4 "Restarting Application via PM2"

cd "$PROJECT_DIR"
ECOSYSTEM_FILE="${PROJECT_DIR}/ecosystem.config.js"

if [ ! -f "$ECOSYSTEM_FILE" ]; then
  error "ecosystem.config.js not found at: $ECOSYSTEM_FILE — aborting."
  exit 1
fi

RUNNING=$(pm2 list 2>/dev/null | grep -c "online" || true)

if [ "$RUNNING" -gt 0 ]; then
  log "Reloading PM2 (zero-downtime)..."
  pm2 reload "$ECOSYSTEM_FILE" --update-env && success "PM2 reloaded." \
    || {
      warn "Reload failed — falling back to pm2 start..."
      pm2 start "$ECOSYSTEM_FILE" && success "PM2 started."
    }
else
  log "No active PM2 processes. Starting fresh..."
  pm2 start "$ECOSYSTEM_FILE" && success "PM2 started."
fi

pm2 save
success "PM2 process list saved."

# ── Done ──────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  ╔══════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}  ║   ✅  DEPLOYMENT COMPLETE                ║${RESET}"
echo -e "${GREEN}${BOLD}  ║   $(date '+%Y-%m-%d %H:%M:%S')                   ║${RESET}"
echo -e "${GREEN}${BOLD}  ╚══════════════════════════════════════════╝${RESET}"
echo ""
DEPLOY_SCRIPT

chmod +x "${PROJECT_DIR}/deploy.sh"
success "deploy.sh written and marked executable."

# ──────────────────────────────────────────────────────────────
# STEP 3 — WRITE SYSTEMD SERVICE FILE
# ──────────────────────────────────────────────────────────────
banner "STEP 3 — Writing systemd Service File"

log "Creating ${SYSTEMD_DIR}/infoboard-deploy@.service ..."

sudo tee "${SYSTEMD_DIR}/infoboard-deploy@.service" > /dev/null << SERVICEEOF
# Auto-generated by bootstrap.sh — do not edit manually.
[Unit]
Description=Infoboard Automated Deployment (user: %i)
After=network-online.target graphical.target
Wants=network-online.target

[Service]
Type=oneshot
User=%i
Group=%i
WorkingDirectory=/home/%i/Desktop/infoboard
Environment=HOME=/home/%i
Environment=USER=%i
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/lib/nodejs/bin
ExecStart=/home/%i/Desktop/infoboard/deploy.sh
TimeoutStartSec=600
RemainAfterExit=no
Restart=no
StandardOutput=journal
StandardError=journal
SyslogIdentifier=infoboard-deploy

[Install]
WantedBy=multi-user.target
SERVICEEOF

success "Service file written."

# ──────────────────────────────────────────────────────────────
# STEP 4 — WRITE SYSTEMD TIMER FILE
# ──────────────────────────────────────────────────────────────
banner "STEP 4 — Writing systemd Timer File"

log "Creating ${SYSTEMD_DIR}/infoboard-deploy@.timer ..."

sudo tee "${SYSTEMD_DIR}/infoboard-deploy@.timer" > /dev/null << TIMEREOF
# Auto-generated by bootstrap.sh — do not edit manually.
[Unit]
Description=Infoboard Deployment Timer (user: %i)
Requires=infoboard-deploy@%i.service

[Timer]
OnBootSec=2min
OnUnitActiveSec=15min
Persistent=true
Unit=infoboard-deploy@%i.service

[Install]
WantedBy=timers.target
TIMEREOF

success "Timer file written."

# ──────────────────────────────────────────────────────────────
# STEP 5 — RELOAD SYSTEMD & ENABLE UNITS
# ──────────────────────────────────────────────────────────────
banner "STEP 5 — Enabling systemd Units"

log "Reloading systemd daemon..."
sudo systemctl daemon-reload
success "Daemon reloaded."

log "Enabling and starting timer: ${SERVICE_NAME}.timer"
sudo systemctl enable "${SERVICE_NAME}.timer"
sudo systemctl start  "${SERVICE_NAME}.timer"
success "Timer enabled and active."

# ──────────────────────────────────────────────────────────────
# STEP 6 — SET UP PM2 STARTUP HOOK
# ──────────────────────────────────────────────────────────────
banner "STEP 6 — Configuring PM2 Startup Hook"

if command -v pm2 &>/dev/null; then
  log "Registering PM2 to launch on system boot..."
  PM2_STARTUP=$(sudo -u "$DEPLOY_USER" bash -c "pm2 startup systemd -u ${DEPLOY_USER} --hp ${DEPLOY_HOME}" 2>&1 | grep "sudo" || true)
  if [ -n "$PM2_STARTUP" ]; then
    eval "$PM2_STARTUP" 2>/dev/null && success "PM2 startup hook registered." || warn "PM2 startup hook command failed — run manually: $PM2_STARTUP"
  else
    success "PM2 startup already configured or no extra step needed."
  fi
else
  warn "PM2 not installed yet — startup hook will be configured on first deploy run."
fi

# ──────────────────────────────────────────────────────────────
# STEP 7 — RUN FIRST DEPLOYMENT NOW
# ──────────────────────────────────────────────────────────────
banner "STEP 7 — Running First Deployment"

log "Triggering initial deployment now..."
echo ""
bash "${PROJECT_DIR}/deploy.sh"

# ──────────────────────────────────────────────────────────────
# DONE — SUMMARY
# ──────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}"
cat << SUMMARY
  ╔═══════════════════════════════════════════════════════════╗
  ║                                                           ║
  ║   🎉  BOOTSTRAP COMPLETE — EVERYTHING IS RUNNING         ║
  ║                                                           ║
  ╠═══════════════════════════════════════════════════════════╣
  ║                                                           ║
  ║  Files written:                                           ║
  ║    ~/Desktop/infoboard/deploy.sh                         ║
  ║    /etc/systemd/system/infoboard-deploy@.service         ║
  ║    /etc/systemd/system/infoboard-deploy@.timer           ║
  ║                                                           ║
  ║  Timer runs:  on boot (+2 min) then every 15 min         ║
  ║                                                           ║
  ╠═══════════════════════════════════════════════════════════╣
  ║                                                           ║
  ║  Useful commands:                                         ║
SUMMARY
echo -e "  ║  Run deploy now:  bash ~/Desktop/infoboard/deploy.sh  ║"
echo -e "  ║  Timer status:    systemctl status ${SERVICE_NAME}.timer"
echo -e "  ║  Live logs:       journalctl -u ${SERVICE_NAME}.service -f"
echo -e "  ║                                                           ║"
echo -e "  ╚═══════════════════════════════════════════════════════════╝"
echo -e "${RESET}"